#! /bin/bash

function num_monitors() {
    xrandr --query | grep -w "connected" | wc -l
}

function primary_monitor() {
    xrandr --query | grep -w "primary" | grep -w "connected" | cut -d ' ' -f 1
} 

function secondary_monitor() {
    xrandr --query | grep -w "connected" | grep -v "primary" | cut -d ' ' -f 1
}

bspc config border_width         	1
bspc config window_gap          	5

bspc config split_ratio          	    0.52
bspc config borderless_monocle   	    true
bspc config gapless_monocle      	    true
bspc config focus_follows_pointer       true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

# use the cursor defined in .Xresources
xsetroot -cursor_name left_ptr &

# start polybar
killall -w polybar
if [[ `num_monitors` -eq "1" ]]; then
    primary=$(primary_monitor)
    bspc monitor %$primary -n "$primary" -d 1 2 3 4 5 6 7 8
    MONITOR=$primary polybar primary &
elif [[ `num_monitors` -eq "2" ]]; then
    primary=$(primary_monitor)
    secondary=$(secondary_monitor)
    bspc monitor %$primary -n "$primary" -d 1 2 3 4 5
    MONITOR=$primary polybar primary &
    bspc monitor %$secondary -n "$secondary" -d 6 7 8 9 10
    MONITOR=$secondary polybar secondary &
fi

sxhkd &

# set the wallpaper
nitrogen --restore &

# start compton
killall -w compton
compton --config ~/.config/compton/compton.conf -b &

# start dunst
killall -w dunst
dunst &

# start nm-applet if installed
if [[ `type nm-applet` ]]; then
  killall -w nm-applet
  nm-applet &
fi
